// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package cloudhsmv2

import (
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/internal/awsutil"
)

var _ aws.Config
var _ = awsutil.Prettify

// Contains information about a backup of an AWS CloudHSM cluster.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/Backup
type Backup struct {
	_ struct{} `type:"structure"`

	// The identifier (ID) of the backup.
	//
	// BackupId is a required field
	BackupId *string `json:"cloudhsmv2:Backup:BackupId" type:"string" required:"true"`

	// The state of the backup.
	BackupState BackupState `json:"cloudhsmv2:Backup:BackupState" type:"string" enum:"true"`

	// The identifier (ID) of the cluster that was backed up.
	ClusterId *string `json:"cloudhsmv2:Backup:ClusterId" type:"string"`

	CopyTimestamp *time.Time `json:"cloudhsmv2:Backup:CopyTimestamp" type:"timestamp" timestampFormat:"unix"`

	// The date and time when the backup was created.
	CreateTimestamp *time.Time `json:"cloudhsmv2:Backup:CreateTimestamp" type:"timestamp" timestampFormat:"unix"`

	// The date and time when the backup will be permanently deleted.
	DeleteTimestamp *time.Time `json:"cloudhsmv2:Backup:DeleteTimestamp" type:"timestamp" timestampFormat:"unix"`

	SourceBackup *string `json:"cloudhsmv2:Backup:SourceBackup" type:"string"`

	SourceCluster *string `json:"cloudhsmv2:Backup:SourceCluster" type:"string"`

	SourceRegion *string `json:"cloudhsmv2:Backup:SourceRegion" type:"string"`
}

// String returns the string representation
func (s Backup) String() string {
	return awsutil.Prettify(s)
}

// Contains one or more certificates or a certificate signing request (CSR).
// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/Certificates
type Certificates struct {
	_ struct{} `type:"structure"`

	// The HSM hardware certificate issued (signed) by AWS CloudHSM.
	AwsHardwareCertificate *string `json:"cloudhsmv2:Certificates:AwsHardwareCertificate" type:"string"`

	// The cluster certificate issued (signed) by the issuing certificate authority
	// (CA) of the cluster's owner.
	ClusterCertificate *string `json:"cloudhsmv2:Certificates:ClusterCertificate" type:"string"`

	// The cluster's certificate signing request (CSR). The CSR exists only when
	// the cluster's state is UNINITIALIZED.
	ClusterCsr *string `json:"cloudhsmv2:Certificates:ClusterCsr" type:"string"`

	// The HSM certificate issued (signed) by the HSM hardware.
	HsmCertificate *string `json:"cloudhsmv2:Certificates:HsmCertificate" type:"string"`

	// The HSM hardware certificate issued (signed) by the hardware manufacturer.
	ManufacturerHardwareCertificate *string `json:"cloudhsmv2:Certificates:ManufacturerHardwareCertificate" type:"string"`
}

// String returns the string representation
func (s Certificates) String() string {
	return awsutil.Prettify(s)
}

// Contains information about an AWS CloudHSM cluster.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/Cluster
type Cluster struct {
	_ struct{} `type:"structure"`

	// The cluster's backup policy.
	BackupPolicy BackupPolicy `json:"cloudhsmv2:Cluster:BackupPolicy" type:"string" enum:"true"`

	// Contains one or more certificates or a certificate signing request (CSR).
	Certificates *Certificates `json:"cloudhsmv2:Cluster:Certificates" type:"structure"`

	// The cluster's identifier (ID).
	ClusterId *string `json:"cloudhsmv2:Cluster:ClusterId" type:"string"`

	// The date and time when the cluster was created.
	CreateTimestamp *time.Time `json:"cloudhsmv2:Cluster:CreateTimestamp" type:"timestamp" timestampFormat:"unix"`

	// The type of HSM that the cluster contains.
	HsmType *string `json:"cloudhsmv2:Cluster:HsmType" type:"string"`

	// Contains information about the HSMs in the cluster.
	Hsms []Hsm `json:"cloudhsmv2:Cluster:Hsms" type:"list"`

	// The default password for the cluster's Pre-Crypto Officer (PRECO) user.
	PreCoPassword *string `json:"cloudhsmv2:Cluster:PreCoPassword" min:"7" type:"string"`

	// The identifier (ID) of the cluster's security group.
	SecurityGroup *string `json:"cloudhsmv2:Cluster:SecurityGroup" type:"string"`

	// The identifier (ID) of the backup used to create the cluster. This value
	// exists only when the cluster was created from a backup.
	SourceBackupId *string `json:"cloudhsmv2:Cluster:SourceBackupId" type:"string"`

	// The cluster's state.
	State ClusterState `json:"cloudhsmv2:Cluster:State" type:"string" enum:"true"`

	// A description of the cluster's state.
	StateMessage *string `json:"cloudhsmv2:Cluster:StateMessage" type:"string"`

	// A map of the cluster's subnets and their corresponding Availability Zones.
	SubnetMapping map[string]string `json:"cloudhsmv2:Cluster:SubnetMapping" type:"map"`

	// The identifier (ID) of the virtual private cloud (VPC) that contains the
	// cluster.
	VpcId *string `json:"cloudhsmv2:Cluster:VpcId" type:"string"`
}

// String returns the string representation
func (s Cluster) String() string {
	return awsutil.Prettify(s)
}

// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/DestinationBackup
type DestinationBackup struct {
	_ struct{} `type:"structure"`

	CreateTimestamp *time.Time `json:"cloudhsmv2:DestinationBackup:CreateTimestamp" type:"timestamp" timestampFormat:"unix"`

	SourceBackup *string `json:"cloudhsmv2:DestinationBackup:SourceBackup" type:"string"`

	SourceCluster *string `json:"cloudhsmv2:DestinationBackup:SourceCluster" type:"string"`

	SourceRegion *string `json:"cloudhsmv2:DestinationBackup:SourceRegion" type:"string"`
}

// String returns the string representation
func (s DestinationBackup) String() string {
	return awsutil.Prettify(s)
}

// Contains information about a hardware security module (HSM) in an AWS CloudHSM
// cluster.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/Hsm
type Hsm struct {
	_ struct{} `type:"structure"`

	// The Availability Zone that contains the HSM.
	AvailabilityZone *string `json:"cloudhsmv2:Hsm:AvailabilityZone" type:"string"`

	// The identifier (ID) of the cluster that contains the HSM.
	ClusterId *string `json:"cloudhsmv2:Hsm:ClusterId" type:"string"`

	// The identifier (ID) of the HSM's elastic network interface (ENI).
	EniId *string `json:"cloudhsmv2:Hsm:EniId" type:"string"`

	// The IP address of the HSM's elastic network interface (ENI).
	EniIp *string `json:"cloudhsmv2:Hsm:EniIp" type:"string"`

	// The HSM's identifier (ID).
	//
	// HsmId is a required field
	HsmId *string `json:"cloudhsmv2:Hsm:HsmId" type:"string" required:"true"`

	// The HSM's state.
	State HsmState `json:"cloudhsmv2:Hsm:State" type:"string" enum:"true"`

	// A description of the HSM's state.
	StateMessage *string `json:"cloudhsmv2:Hsm:StateMessage" type:"string"`

	// The subnet that contains the HSM's elastic network interface (ENI).
	SubnetId *string `json:"cloudhsmv2:Hsm:SubnetId" type:"string"`
}

// String returns the string representation
func (s Hsm) String() string {
	return awsutil.Prettify(s)
}

// Contains a tag. A tag is a key-value pair.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/cloudhsmv2-2017-04-28/Tag
type Tag struct {
	_ struct{} `type:"structure"`

	// The key of the tag.
	//
	// Key is a required field
	Key *string `json:"cloudhsmv2:Tag:Key" min:"1" type:"string" required:"true"`

	// The value of the tag.
	//
	// Value is a required field
	Value *string `json:"cloudhsmv2:Tag:Value" type:"string" required:"true"`
}

// String returns the string representation
func (s Tag) String() string {
	return awsutil.Prettify(s)
}

// Validate inspects the fields of the type to determine if they are valid.
func (s *Tag) Validate() error {
	invalidParams := aws.ErrInvalidParams{Context: "Tag"}

	if s.Key == nil {
		invalidParams.Add(aws.NewErrParamRequired("Key"))
	}
	if s.Key != nil && len(*s.Key) < 1 {
		invalidParams.Add(aws.NewErrParamMinLen("Key", 1))
	}

	if s.Value == nil {
		invalidParams.Add(aws.NewErrParamRequired("Value"))
	}

	if invalidParams.Len() > 0 {
		return invalidParams
	}
	return nil
}
