// Code generated by private/model/cli/gen-api/main.go. DO NOT EDIT.

package opsworkscm

import (
	"time"

	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/internal/awsutil"
)

var _ aws.Config
var _ = awsutil.Prettify

// Stores account attributes.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/opsworkscm-2016-11-01/AccountAttribute
type AccountAttribute struct {
	_ struct{} `type:"structure"`

	// The maximum allowed value.
	Maximum *int64 `json:"opsworks-cm:AccountAttribute:Maximum" type:"integer"`

	// The attribute name. The following are supported attribute names.
	//
	//    * ServerLimit: The number of current servers/maximum number of servers
	//    allowed. By default, you can have a maximum of 10 servers.
	//
	//    * ManualBackupLimit: The number of current manual backups/maximum number
	//    of backups allowed. By default, you can have a maximum of 50 manual backups
	//    saved.
	Name *string `json:"opsworks-cm:AccountAttribute:Name" type:"string"`

	// The current usage, such as the current number of servers that are associated
	// with the account.
	Used *int64 `json:"opsworks-cm:AccountAttribute:Used" type:"integer"`
}

// String returns the string representation
func (s AccountAttribute) String() string {
	return awsutil.Prettify(s)
}

// Describes a single backup.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/opsworkscm-2016-11-01/Backup
type Backup struct {
	_ struct{} `type:"structure"`

	// The ARN of the backup.
	BackupArn *string `json:"opsworks-cm:Backup:BackupArn" type:"string"`

	// The generated ID of the backup. Example: myServerName-yyyyMMddHHmmssSSS
	BackupId *string `json:"opsworks-cm:Backup:BackupId" type:"string"`

	// The backup type. Valid values are automated or manual.
	BackupType BackupType `json:"opsworks-cm:Backup:BackupType" type:"string" enum:"true"`

	// The time stamp when the backup was created in the database. Example: 2016-07-29T13:38:47.520Z
	CreatedAt *time.Time `json:"opsworks-cm:Backup:CreatedAt" type:"timestamp" timestampFormat:"unix"`

	// A user-provided description for a manual backup. This field is empty for
	// automated backups.
	Description *string `json:"opsworks-cm:Backup:Description" type:"string"`

	// The engine type that is obtained from the server when the backup is created.
	Engine *string `json:"opsworks-cm:Backup:Engine" type:"string"`

	// The engine model that is obtained from the server when the backup is created.
	EngineModel *string `json:"opsworks-cm:Backup:EngineModel" type:"string"`

	// The engine version that is obtained from the server when the backup is created.
	EngineVersion *string `json:"opsworks-cm:Backup:EngineVersion" type:"string"`

	// The EC2 instance profile ARN that is obtained from the server when the backup
	// is created. Because this value is stored, you are not required to provide
	// the InstanceProfileArn again if you restore a backup.
	InstanceProfileArn *string `json:"opsworks-cm:Backup:InstanceProfileArn" type:"string"`

	// The instance type that is obtained from the server when the backup is created.
	InstanceType *string `json:"opsworks-cm:Backup:InstanceType" type:"string"`

	// The key pair that is obtained from the server when the backup is created.
	KeyPair *string `json:"opsworks-cm:Backup:KeyPair" type:"string"`

	// The preferred backup period that is obtained from the server when the backup
	// is created.
	PreferredBackupWindow *string `json:"opsworks-cm:Backup:PreferredBackupWindow" type:"string"`

	// The preferred maintenance period that is obtained from the server when the
	// backup is created.
	PreferredMaintenanceWindow *string `json:"opsworks-cm:Backup:PreferredMaintenanceWindow" type:"string"`

	// This field is deprecated and is no longer used.
	S3DataSize *int64 `json:"opsworks-cm:Backup:S3DataSize" deprecated:"true" type:"integer"`

	// This field is deprecated and is no longer used.
	S3DataUrl *string `json:"opsworks-cm:Backup:S3DataUrl" deprecated:"true" type:"string"`

	// The Amazon S3 URL of the backup's log file.
	S3LogUrl *string `json:"opsworks-cm:Backup:S3LogUrl" type:"string"`

	// The security group IDs that are obtained from the server when the backup
	// is created.
	SecurityGroupIds []string `json:"opsworks-cm:Backup:SecurityGroupIds" type:"list"`

	// The name of the server from which the backup was made.
	ServerName *string `json:"opsworks-cm:Backup:ServerName" min:"1" type:"string"`

	// The service role ARN that is obtained from the server when the backup is
	// created.
	ServiceRoleArn *string `json:"opsworks-cm:Backup:ServiceRoleArn" type:"string"`

	// The status of a backup while in progress.
	Status BackupStatus `json:"opsworks-cm:Backup:Status" type:"string" enum:"true"`

	// An informational message about backup status.
	StatusDescription *string `json:"opsworks-cm:Backup:StatusDescription" type:"string"`

	// The subnet IDs that are obtained from the server when the backup is created.
	SubnetIds []string `json:"opsworks-cm:Backup:SubnetIds" type:"list"`

	// The version of AWS OpsWorks CM-specific tools that is obtained from the server
	// when the backup is created.
	ToolsVersion *string `json:"opsworks-cm:Backup:ToolsVersion" type:"string"`

	// The IAM user ARN of the requester for manual backups. This field is empty
	// for automated backups.
	UserArn *string `json:"opsworks-cm:Backup:UserArn" type:"string"`
}

// String returns the string representation
func (s Backup) String() string {
	return awsutil.Prettify(s)
}

// A name and value pair that is specific to the engine of the server.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/opsworkscm-2016-11-01/EngineAttribute
type EngineAttribute struct {
	_ struct{} `type:"structure"`

	// The name of the engine attribute.
	Name *string `json:"opsworks-cm:EngineAttribute:Name" type:"string"`

	// The value of the engine attribute.
	Value *string `json:"opsworks-cm:EngineAttribute:Value" type:"string"`
}

// String returns the string representation
func (s EngineAttribute) String() string {
	return awsutil.Prettify(s)
}

// Describes a configuration management server.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/opsworkscm-2016-11-01/Server
type Server struct {
	_ struct{} `type:"structure"`

	// Associate a public IP address with a server that you are launching.
	AssociatePublicIpAddress *bool `json:"opsworks-cm:Server:AssociatePublicIpAddress" type:"boolean"`

	// The number of automated backups to keep.
	BackupRetentionCount *int64 `json:"opsworks-cm:Server:BackupRetentionCount" type:"integer"`

	// The ARN of the CloudFormation stack that was used to create the server.
	CloudFormationStackArn *string `json:"opsworks-cm:Server:CloudFormationStackArn" type:"string"`

	// Time stamp of server creation. Example 2016-07-29T13:38:47.520Z
	CreatedAt *time.Time `json:"opsworks-cm:Server:CreatedAt" type:"timestamp" timestampFormat:"unix"`

	// Disables automated backups. The number of stored backups is dependent on
	// the value of PreferredBackupCount.
	DisableAutomatedBackup *bool `json:"opsworks-cm:Server:DisableAutomatedBackup" type:"boolean"`

	// A DNS name that can be used to access the engine. Example: myserver-asdfghjkl.us-east-1.opsworks.io
	Endpoint *string `json:"opsworks-cm:Server:Endpoint" type:"string"`

	// The engine type of the server. Valid values in this release include ChefAutomate
	// and Puppet.
	Engine *string `json:"opsworks-cm:Server:Engine" type:"string"`

	// The response of a createServer() request returns the master credential to
	// access the server in EngineAttributes. These credentials are not stored by
	// AWS OpsWorks CM; they are returned only as part of the result of createServer().
	//
	// Attributes returned in a createServer response for Chef
	//
	//    * CHEF_AUTOMATE_PIVOTAL_KEY: A base64-encoded RSA private key that is
	//    generated by AWS OpsWorks for Chef Automate. This private key is required
	//    to access the Chef API.
	//
	//    * CHEF_STARTER_KIT: A base64-encoded ZIP file. The ZIP file contains a
	//    Chef starter kit, which includes a README, a configuration file, and the
	//    required RSA private key. Save this file, unzip it, and then change to
	//    the directory where you've unzipped the file contents. From this directory,
	//    you can run Knife commands.
	//
	// Attributes returned in a createServer response for Puppet
	//
	//    * PUPPET_STARTER_KIT: A base64-encoded ZIP file. The ZIP file contains
	//    a Puppet starter kit, including a README and a required private key. Save
	//    this file, unzip it, and then change to the directory where you've unzipped
	//    the file contents.
	//
	//    * PUPPET_ADMIN_PASSWORD: An administrator password that you can use to
	//    sign in to the Puppet Enterprise console after the server is online.
	EngineAttributes []EngineAttribute `json:"opsworks-cm:Server:EngineAttributes" type:"list"`

	// The engine model of the server. Valid values in this release include Monolithic
	// for Puppet and Single for Chef.
	EngineModel *string `json:"opsworks-cm:Server:EngineModel" type:"string"`

	// The engine version of the server. For a Chef server, the valid value for
	// EngineVersion is currently 12. For a Puppet server, the valid value is 2017.
	EngineVersion *string `json:"opsworks-cm:Server:EngineVersion" type:"string"`

	// The instance profile ARN of the server.
	InstanceProfileArn *string `json:"opsworks-cm:Server:InstanceProfileArn" type:"string"`

	// The instance type for the server, as specified in the CloudFormation stack.
	// This might not be the same instance type that is shown in the EC2 console.
	InstanceType *string `json:"opsworks-cm:Server:InstanceType" type:"string"`

	// The key pair associated with the server.
	KeyPair *string `json:"opsworks-cm:Server:KeyPair" type:"string"`

	// The status of the most recent server maintenance run. Shows SUCCESS or FAILED.
	MaintenanceStatus MaintenanceStatus `json:"opsworks-cm:Server:MaintenanceStatus" type:"string" enum:"true"`

	// The preferred backup period specified for the server.
	PreferredBackupWindow *string `json:"opsworks-cm:Server:PreferredBackupWindow" type:"string"`

	// The preferred maintenance period specified for the server.
	PreferredMaintenanceWindow *string `json:"opsworks-cm:Server:PreferredMaintenanceWindow" type:"string"`

	// The security group IDs for the server, as specified in the CloudFormation
	// stack. These might not be the same security groups that are shown in the
	// EC2 console.
	SecurityGroupIds []string `json:"opsworks-cm:Server:SecurityGroupIds" type:"list"`

	// The ARN of the server.
	ServerArn *string `json:"opsworks-cm:Server:ServerArn" type:"string"`

	// The name of the server.
	ServerName *string `json:"opsworks-cm:Server:ServerName" type:"string"`

	// The service role ARN used to create the server.
	ServiceRoleArn *string `json:"opsworks-cm:Server:ServiceRoleArn" type:"string"`

	// The server's status. This field displays the states of actions in progress,
	// such as creating, running, or backing up the server, as well as the server's
	// health state.
	Status ServerStatus `json:"opsworks-cm:Server:Status" type:"string" enum:"true"`

	// Depending on the server status, this field has either a human-readable message
	// (such as a create or backup error), or an escaped block of JSON (used for
	// health check results).
	StatusReason *string `json:"opsworks-cm:Server:StatusReason" type:"string"`

	// The subnet IDs specified in a CreateServer request.
	SubnetIds []string `json:"opsworks-cm:Server:SubnetIds" type:"list"`
}

// String returns the string representation
func (s Server) String() string {
	return awsutil.Prettify(s)
}

// An event that is related to the server, such as the start of maintenance
// or backup.
// Please also see https://docs.aws.amazon.com/goto/WebAPI/opsworkscm-2016-11-01/ServerEvent
type ServerEvent struct {
	_ struct{} `type:"structure"`

	// The time when the event occurred.
	CreatedAt *time.Time `json:"opsworks-cm:ServerEvent:CreatedAt" type:"timestamp" timestampFormat:"unix"`

	// The Amazon S3 URL of the event's log file.
	LogUrl *string `json:"opsworks-cm:ServerEvent:LogUrl" type:"string"`

	// A human-readable informational or status message.
	Message *string `json:"opsworks-cm:ServerEvent:Message" type:"string"`

	// The name of the server on or for which the event occurred.
	ServerName *string `json:"opsworks-cm:ServerEvent:ServerName" type:"string"`
}

// String returns the string representation
func (s ServerEvent) String() string {
	return awsutil.Prettify(s)
}
